version: '3'

services:
  keycloak-proxy:
    image: jboss/keycloak-proxy:4.3.0.Final

    ports:
      - 8180:8180

    environment:
      - TZ=America/New_York

    volumes:
      - ./keycloak-proxy.config.json:/opt/jboss/conf/proxy.json
  elk:
    build: .
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    environment:
      - TZ=America/New_York
      - ES_HEAP_SIZE=1g
      - LS_HEAP_SIZE=1g
    volumes:
      - elk-data:/var/lib/elasticsearch
volumes:
  elk-data:
